//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: CmdID.proto
// Note: requires additional types generated from: EnterGame.proto
namespace SLMS
{
    [global::ProtoBuf.ProtoContract(Name=@"CmdID")]
    public enum CmdID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PartList", Value=98)]
      CMD_PartList = 98,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CheckLogin", Value=99)]
      CMD_CheckLogin = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_Login2Game", Value=100)]
      CMD_Login2Game = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CreateRole", Value=101)]
      CMD_CreateRole = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_EnterGame", Value=102)]
      CMD_EnterGame = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_Logout", Value=103)]
      CMD_Logout = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_Rename", Value=104)]
      CMD_Rename = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_RoleInfo", Value=105)]
      CMD_RoleInfo = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_SynAttr", Value=111)]
      CMD_SynAttr = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_SynTimer", Value=112)]
      CMD_SynTimer = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_SynRedSpot", Value=113)]
      CMD_SynRedSpot = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PlaneList", Value=121)]
      CMD_PlaneList = 121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PlaneBuy", Value=122)]
      CMD_PlaneBuy = 122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PlaneUpgrade", Value=123)]
      CMD_PlaneUpgrade = 123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PlaneFight", Value=124)]
      CMD_PlaneFight = 124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PlaneInherit", Value=125)]
      CMD_PlaneInherit = 125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PilotList", Value=141)]
      CMD_PilotList = 141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PilotBuy", Value=142)]
      CMD_PilotBuy = 142,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PilotUpgrade", Value=143)]
      CMD_PilotUpgrade = 143,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_PilotInteract", Value=144)]
      CMD_PilotInteract = 144,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_NotifyTip", Value=202)]
      CMD_NotifyTip = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_COMMAND_MAX", Value=1024)]
      CLIENT_COMMAND_MAX = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CacheCommit", Value=1161)]
      CMD_CacheCommit = 1161,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CacheDelete", Value=1162)]
      CMD_CacheDelete = 1162,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CacheQuery", Value=1163)]
      CMD_CacheQuery = 1163,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CacheBatchQuery", Value=1164)]
      CMD_CacheBatchQuery = 1164,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CacheDataWriteBack", Value=1165)]
      CMD_CacheDataWriteBack = 1165,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CacheStatus", Value=1166)]
      CMD_CacheStatus = 1166,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GetPartInfo", Value=1170)]
      CMD_GetPartInfo = 1170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_SetPartInfo", Value=1171)]
      CMD_SetPartInfo = 1171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_OnlineReport", Value=1172)]
      CMD_OnlineReport = 1172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_NewUserReport", Value=1173)]
      CMD_NewUserReport = 1173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_FoodstuffSetData", Value=1174)]
      CMD_FoodstuffSetData = 1174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_SetUserProfile", Value=1176)]
      CMD_SetUserProfile = 1176,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GetUserProfile", Value=1177)]
      CMD_GetUserProfile = 1177,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_FoodstuffGetProfile", Value=1178)]
      CMD_FoodstuffGetProfile = 1178,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CheckSession", Value=1181)]
      CMD_CheckSession = 1181,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_CheckPayOrder", Value=1182)]
      CMD_CheckPayOrder = 1182,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_Report2Platform", Value=1183)]
      CMD_Report2Platform = 1183,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_RefreshConfig", Value=1184)]
      CMD_RefreshConfig = 1184,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_RefreshRoleLogin", Value=1185)]
      CMD_RefreshRoleLogin = 1185,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GetAccount", Value=1186)]
      CMD_GetAccount = 1186,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_SetLoginInfo", Value=1187)]
      CMD_SetLoginInfo = 1187,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_UpdateAccount", Value=1188)]
      CMD_UpdateAccount = 1188,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GetAccountByUin", Value=1189)]
      CMD_GetAccountByUin = 1189,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_ReportOnlineRole", Value=1190)]
      CMD_ReportOnlineRole = 1190,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMAND_MAX", Value=2048)]
      COMMAND_MAX = 2048
    }
  
}