//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Common.proto
namespace SLMS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleInfo")]
  public partial class RoleInfo : global::ProtoBuf.IExtensible
  {
    public RoleInfo() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint? _lvl;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lvl
    {
      get { return _lvl?? default(uint); }
      set { _lvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lvlSpecified
    {
      get { return this._lvl != null; }
      set { if (value == (this._lvl== null)) this._lvl = value ? this.lvl : (uint?)null; }
    }
    private bool ShouldSerializelvl() { return lvlSpecified; }
    private void Resetlvl() { lvlSpecified = false; }
    
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private bool? _sex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sex
    {
      get { return _sex?? default(bool); }
      set { _sex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sexSpecified
    {
      get { return this._sex != null; }
      set { if (value == (this._sex== null)) this._sex = value ? this.sex : (bool?)null; }
    }
    private bool ShouldSerializesex() { return sexSpecified; }
    private void Resetsex() { sexSpecified = false; }
    
    private string _icon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon?? ""; }
      set { _icon = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool iconSpecified
    {
      get { return this._icon != null; }
      set { if (value == (this._icon== null)) this._icon = value ? this.icon : (string)null; }
    }
    private bool ShouldSerializeicon() { return iconSpecified; }
    private void Reseticon() { iconSpecified = false; }
    
    private uint? _lastLoginTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lastLoginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastLoginTime
    {
      get { return _lastLoginTime?? default(uint); }
      set { _lastLoginTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastLoginTimeSpecified
    {
      get { return this._lastLoginTime != null; }
      set { if (value == (this._lastLoginTime== null)) this._lastLoginTime = value ? this.lastLoginTime : (uint?)null; }
    }
    private bool ShouldSerializelastLoginTime() { return lastLoginTimeSpecified; }
    private void ResetlastLoginTime() { lastLoginTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResType")]
    public enum ResType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_NULL", Value=0)]
      RT_NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_DIAMOND", Value=1)]
      RT_DIAMOND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_GOLD", Value=2)]
      RT_GOLD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_ENERGY", Value=3)]
      RT_ENERGY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_PLANE", Value=4)]
      RT_PLANE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_PILOT", Value=5)]
      RT_PILOT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_ITEM", Value=6)]
      RT_ITEM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_CAPTAIN_EXP", Value=7)]
      RT_CAPTAIN_EXP = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_VIP_EXP", Value=12)]
      RT_VIP_EXP = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_ICON", Value=16)]
      RT_ICON = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_ICON_FRAME", Value=17)]
      RT_ICON_FRAME = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RT_MAX", Value=32)]
      RT_MAX = 32
    }
  
}