//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: EnterGame.proto
// Note: requires additional types generated from: ResultCode.proto
namespace SLMS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRole")]
  public partial class GameRole : global::ProtoBuf.IExtensible
  {
    public GameRole() {}
    
    private ulong _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _part;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"part", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int part
    {
      get { return _part; }
      set { _part = value; }
    }
    private uint _lastLoginTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lastLoginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastLoginTime
    {
      get { return _lastLoginTime; }
      set { _lastLoginTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleBaseInfo")]
  public partial class RoleBaseInfo : global::ProtoBuf.IExtensible
  {
    public RoleBaseInfo() {}
    
    private ulong _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GamePart")]
  public partial class GamePart : global::ProtoBuf.IExtensible
  {
    public GamePart() {}
    
    private int _partId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"partId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int partId
    {
      get { return _partId; }
      set { _partId = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private int _fixflag;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fixflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fixflag
    {
      get { return _fixflag; }
      set { _fixflag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameAccount")]
  public partial class GameAccount : global::ProtoBuf.IExtensible
  {
    public GameAccount() {}
    
    private ulong _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _sid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private readonly global::System.Collections.Generic.List<SLMS.GameRole> _roles = new global::System.Collections.Generic.List<SLMS.GameRole>();
    [global::ProtoBuf.ProtoMember(3, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SLMS.GameRole> roles
    {
      get { return _roles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csCheckLogin")]
  public partial class csCheckLogin : global::ProtoBuf.IExtensible
  {
    public csCheckLogin() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId?? ""; }
      set { _userId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userIdSpecified
    {
      get { return this._userId != null; }
      set { if (value == (this._userId== null)) this._userId = value ? this.userId : (string)null; }
    }
    private bool ShouldSerializeuserId() { return userIdSpecified; }
    private void ResetuserId() { userIdSpecified = false; }
    
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token?? ""; }
      set { _token = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tokenSpecified
    {
      get { return this._token != null; }
      set { if (value == (this._token== null)) this._token = value ? this.token : (string)null; }
    }
    private bool ShouldSerializetoken() { return tokenSpecified; }
    private void Resettoken() { tokenSpecified = false; }
    
    private string _sdk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sdk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sdk
    {
      get { return _sdk?? ""; }
      set { _sdk = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sdkSpecified
    {
      get { return this._sdk != null; }
      set { if (value == (this._sdk== null)) this._sdk = value ? this.sdk : (string)null; }
    }
    private bool ShouldSerializesdk() { return sdkSpecified; }
    private void Resetsdk() { sdkSpecified = false; }
    
    private string _app;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"app", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string app
    {
      get { return _app?? ""; }
      set { _app = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool appSpecified
    {
      get { return this._app != null; }
      set { if (value == (this._app== null)) this._app = value ? this.app : (string)null; }
    }
    private bool ShouldSerializeapp() { return appSpecified; }
    private void Resetapp() { appSpecified = false; }
    
    private string _device;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"device", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device
    {
      get { return _device?? ""; }
      set { _device = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deviceSpecified
    {
      get { return this._device != null; }
      set { if (value == (this._device== null)) this._device = value ? this.device : (string)null; }
    }
    private bool ShouldSerializedevice() { return deviceSpecified; }
    private void Resetdevice() { deviceSpecified = false; }
    
    private string _device_guid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"device_guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_guid
    {
      get { return _device_guid?? ""; }
      set { _device_guid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool device_guidSpecified
    {
      get { return this._device_guid != null; }
      set { if (value == (this._device_guid== null)) this._device_guid = value ? this.device_guid : (string)null; }
    }
    private bool ShouldSerializedevice_guid() { return device_guidSpecified; }
    private void Resetdevice_guid() { device_guidSpecified = false; }
    
    private string _os;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string os
    {
      get { return _os?? ""; }
      set { _os = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool osSpecified
    {
      get { return this._os != null; }
      set { if (value == (this._os== null)) this._os = value ? this.os : (string)null; }
    }
    private bool ShouldSerializeos() { return osSpecified; }
    private void Resetos() { osSpecified = false; }
    
    private string _os_version;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"os_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string os_version
    {
      get { return _os_version?? ""; }
      set { _os_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool os_versionSpecified
    {
      get { return this._os_version != null; }
      set { if (value == (this._os_version== null)) this._os_version = value ? this.os_version : (string)null; }
    }
    private bool ShouldSerializeos_version() { return os_versionSpecified; }
    private void Resetos_version() { os_versionSpecified = false; }
    
    private string _client_version;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"client_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string client_version
    {
      get { return _client_version?? ""; }
      set { _client_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool client_versionSpecified
    {
      get { return this._client_version != null; }
      set { if (value == (this._client_version== null)) this._client_version = value ? this.client_version : (string)null; }
    }
    private bool ShouldSerializeclient_version() { return client_versionSpecified; }
    private void Resetclient_version() { client_versionSpecified = false; }
    
    private string _reserved_value;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"reserved_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reserved_value
    {
      get { return _reserved_value?? ""; }
      set { _reserved_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reserved_valueSpecified
    {
      get { return this._reserved_value != null; }
      set { if (value == (this._reserved_value== null)) this._reserved_value = value ? this.reserved_value : (string)null; }
    }
    private bool ShouldSerializereserved_value() { return reserved_valueSpecified; }
    private void Resetreserved_value() { reserved_valueSpecified = false; }
    
    private uint? _current_version;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"current_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint current_version
    {
      get { return _current_version?? default(uint); }
      set { _current_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool current_versionSpecified
    {
      get { return this._current_version != null; }
      set { if (value == (this._current_version== null)) this._current_version = value ? this.current_version : (uint?)null; }
    }
    private bool ShouldSerializecurrent_version() { return current_versionSpecified; }
    private void Resetcurrent_version() { current_versionSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scCheckLogin")]
  public partial class scCheckLogin : global::ProtoBuf.IExtensible
  {
    public scCheckLogin() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private SLMS.GameAccount _account = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SLMS.GameAccount account
    {
      get { return _account; }
      set { _account = value; }
    }
    private readonly global::System.Collections.Generic.List<SLMS.GamePart> _gameParts = new global::System.Collections.Generic.List<SLMS.GamePart>();
    [global::ProtoBuf.ProtoMember(3, Name=@"gameParts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SLMS.GamePart> gameParts
    {
      get { return _gameParts; }
    }
  
    private string _userid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userid
    {
      get { return _userid?? ""; }
      set { _userid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool useridSpecified
    {
      get { return this._userid != null; }
      set { if (value == (this._userid== null)) this._userid = value ? this.userid : (string)null; }
    }
    private bool ShouldSerializeuserid() { return useridSpecified; }
    private void Resetuserid() { useridSpecified = false; }
    
    private int? _part_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"part_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int part_id
    {
      get { return _part_id?? default(int); }
      set { _part_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool part_idSpecified
    {
      get { return this._part_id != null; }
      set { if (value == (this._part_id== null)) this._part_id = value ? this.part_id : (int?)null; }
    }
    private bool ShouldSerializepart_id() { return part_idSpecified; }
    private void Resetpart_id() { part_idSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _role_part = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"role_part", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> role_part
    {
      get { return _role_part; }
    }
  
    private string _test_ip;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"test_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string test_ip
    {
      get { return _test_ip?? ""; }
      set { _test_ip = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool test_ipSpecified
    {
      get { return this._test_ip != null; }
      set { if (value == (this._test_ip== null)) this._test_ip = value ? this.test_ip : (string)null; }
    }
    private bool ShouldSerializetest_ip() { return test_ipSpecified; }
    private void Resettest_ip() { test_ipSpecified = false; }
    
    private uint? _test_port;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"test_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint test_port
    {
      get { return _test_port?? default(uint); }
      set { _test_port = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool test_portSpecified
    {
      get { return this._test_port != null; }
      set { if (value == (this._test_port== null)) this._test_port = value ? this.test_port : (uint?)null; }
    }
    private bool ShouldSerializetest_port() { return test_portSpecified; }
    private void Resettest_port() { test_portSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csPartList")]
  public partial class csPartList : global::ProtoBuf.IExtensible
  {
    public csPartList() {}
    
    private string _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _sdk;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sdk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sdk
    {
      get { return _sdk; }
      set { _sdk = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scPartList")]
  public partial class scPartList : global::ProtoBuf.IExtensible
  {
    public scPartList() {}
    
    private readonly global::System.Collections.Generic.List<SLMS.GamePart> _parts = new global::System.Collections.Generic.List<SLMS.GamePart>();
    [global::ProtoBuf.ProtoMember(1, Name=@"parts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SLMS.GamePart> parts
    {
      get { return _parts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csEnterGame")]
  public partial class csEnterGame : global::ProtoBuf.IExtensible
  {
    public csEnterGame() {}
    
    private string _device_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _uin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _sdk;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sdk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sdk
    {
      get { return _sdk; }
      set { _sdk = value; }
    }
    private string _device;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"device", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device
    {
      get { return _device; }
      set { _device = value; }
    }
    private string _sys;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sys
    {
      get { return _sys; }
      set { _sys = value; }
    }
    private string _sys_version;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"sys_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sys_version
    {
      get { return _sys_version; }
      set { _sys_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scEnterGame")]
  public partial class scEnterGame : global::ProtoBuf.IExtensible
  {
    public scEnterGame() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csLogin2Game")]
  public partial class csLogin2Game : global::ProtoBuf.IExtensible
  {
    public csLogin2Game() {}
    
    private ulong _uin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private int _reconnect;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"reconnect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reconnect
    {
      get { return _reconnect; }
      set { _reconnect = value; }
    }
    private string _sid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sid
    {
      get { return _sid; }
      set { _sid = value; }
    }
    private int? _partid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"partid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int partid
    {
      get { return _partid?? default(int); }
      set { _partid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool partidSpecified
    {
      get { return this._partid != null; }
      set { if (value == (this._partid== null)) this._partid = value ? this.partid : (int?)null; }
    }
    private bool ShouldSerializepartid() { return partidSpecified; }
    private void Resetpartid() { partidSpecified = false; }
    
    private bool? _skip_login;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skip_login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool skip_login
    {
      get { return _skip_login?? default(bool); }
      set { _skip_login = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skip_loginSpecified
    {
      get { return this._skip_login != null; }
      set { if (value == (this._skip_login== null)) this._skip_login = value ? this.skip_login : (bool?)null; }
    }
    private bool ShouldSerializeskip_login() { return skip_loginSpecified; }
    private void Resetskip_login() { skip_loginSpecified = false; }
    
    private uint _client_data_version;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"client_data_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint client_data_version
    {
      get { return _client_data_version; }
      set { _client_data_version = value; }
    }
    private string _device_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _str_uin;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"str_uin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_uin
    {
      get { return _str_uin; }
      set { _str_uin = value; }
    }
    private string _sdk;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"sdk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sdk
    {
      get { return _sdk; }
      set { _sdk = value; }
    }
    private string _device;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"device", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device
    {
      get { return _device; }
      set { _device = value; }
    }
    private string _sys;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"sys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sys
    {
      get { return _sys; }
      set { _sys = value; }
    }
    private string _sys_version;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"sys_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sys_version
    {
      get { return _sys_version; }
      set { _sys_version = value; }
    }
    private uint _client_version;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"client_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint client_version
    {
      get { return _client_version; }
      set { _client_version = value; }
    }
    private uint? _config_version;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"config_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint config_version
    {
      get { return _config_version?? default(uint); }
      set { _config_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool config_versionSpecified
    {
      get { return this._config_version != null; }
      set { if (value == (this._config_version== null)) this._config_version = value ? this.config_version : (uint?)null; }
    }
    private bool ShouldSerializeconfig_version() { return config_versionSpecified; }
    private void Resetconfig_version() { config_versionSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scLogin2Game")]
  public partial class scLogin2Game : global::ProtoBuf.IExtensible
  {
    public scLogin2Game() {}
    
    private SLMS.ResultCode _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SLMS.ResultCode ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private int? _reconnect;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reconnect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reconnect
    {
      get { return _reconnect?? default(int); }
      set { _reconnect = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reconnectSpecified
    {
      get { return this._reconnect != null; }
      set { if (value == (this._reconnect== null)) this._reconnect = value ? this.reconnect : (int?)null; }
    }
    private bool ShouldSerializereconnect() { return reconnectSpecified; }
    private void Resetreconnect() { reconnectSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<SLMS.RoleBaseInfo> _roles = new global::System.Collections.Generic.List<SLMS.RoleBaseInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SLMS.RoleBaseInfo> roles
    {
      get { return _roles; }
    }
  
    private uint? _serverStamp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"serverStamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverStamp
    {
      get { return _serverStamp?? default(uint); }
      set { _serverStamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serverStampSpecified
    {
      get { return this._serverStamp != null; }
      set { if (value == (this._serverStamp== null)) this._serverStamp = value ? this.serverStamp : (uint?)null; }
    }
    private bool ShouldSerializeserverStamp() { return serverStampSpecified; }
    private void ResetserverStamp() { serverStampSpecified = false; }
    
    private uint? _gmFlag;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gmFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gmFlag
    {
      get { return _gmFlag?? default(uint); }
      set { _gmFlag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gmFlagSpecified
    {
      get { return this._gmFlag != null; }
      set { if (value == (this._gmFlag== null)) this._gmFlag = value ? this.gmFlag : (uint?)null; }
    }
    private bool ShouldSerializegmFlag() { return gmFlagSpecified; }
    private void ResetgmFlag() { gmFlagSpecified = false; }
    
    private uint? _dataVersion;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dataVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataVersion
    {
      get { return _dataVersion?? default(uint); }
      set { _dataVersion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataVersionSpecified
    {
      get { return this._dataVersion != null; }
      set { if (value == (this._dataVersion== null)) this._dataVersion = value ? this.dataVersion : (uint?)null; }
    }
    private bool ShouldSerializedataVersion() { return dataVersionSpecified; }
    private void ResetdataVersion() { dataVersionSpecified = false; }
    
    private uint? _exchangeCodeFlag;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"exchangeCodeFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exchangeCodeFlag
    {
      get { return _exchangeCodeFlag?? default(uint); }
      set { _exchangeCodeFlag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool exchangeCodeFlagSpecified
    {
      get { return this._exchangeCodeFlag != null; }
      set { if (value == (this._exchangeCodeFlag== null)) this._exchangeCodeFlag = value ? this.exchangeCodeFlag : (uint?)null; }
    }
    private bool ShouldSerializeexchangeCodeFlag() { return exchangeCodeFlagSpecified; }
    private void ResetexchangeCodeFlag() { exchangeCodeFlagSpecified = false; }
    
    private uint? _system_enable_flag;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"system_enable_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint system_enable_flag
    {
      get { return _system_enable_flag?? default(uint); }
      set { _system_enable_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool system_enable_flagSpecified
    {
      get { return this._system_enable_flag != null; }
      set { if (value == (this._system_enable_flag== null)) this._system_enable_flag = value ? this.system_enable_flag : (uint?)null; }
    }
    private bool ShouldSerializesystem_enable_flag() { return system_enable_flagSpecified; }
    private void Resetsystem_enable_flag() { system_enable_flagSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csCreateRole")]
  public partial class csCreateRole : global::ProtoBuf.IExtensible
  {
    public csCreateRole() {}
    
    private bool _sex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _device_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device_id
    {
      get { return _device_id; }
      set { _device_id = value; }
    }
    private string _uin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uin
    {
      get { return _uin; }
      set { _uin = value; }
    }
    private string _sdk;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"sdk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sdk
    {
      get { return _sdk; }
      set { _sdk = value; }
    }
    private string _device;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"device", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string device
    {
      get { return _device; }
      set { _device = value; }
    }
    private string _sys;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sys
    {
      get { return _sys; }
      set { _sys = value; }
    }
    private string _sys_version;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"sys_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sys_version
    {
      get { return _sys_version; }
      set { _sys_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scCreateRole")]
  public partial class scCreateRole : global::ProtoBuf.IExtensible
  {
    public scCreateRole() {}
    
    private SLMS.ResultCode _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SLMS.ResultCode ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private SLMS.RoleBaseInfo _newRole = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"newRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SLMS.RoleBaseInfo newRole
    {
      get { return _newRole; }
      set { _newRole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csLogout")]
  public partial class csLogout : global::ProtoBuf.IExtensible
  {
    public csLogout() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scLogout")]
  public partial class scLogout : global::ProtoBuf.IExtensible
  {
    public scLogout() {}
    
    private SLMS.ResultCode _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SLMS.ResultCode ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PartStatus")]
    public enum PartStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_NORMAL", Value=0)]
      PS_NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_NEW", Value=1)]
      PS_NEW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_HOT", Value=2)]
      PS_HOT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PS_SMOOTH", Value=3)]
      PS_SMOOTH = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameChannelType")]
    public enum GameChannelType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_NULL", Value=0)]
      GCT_NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_UC", Value=1)]
      GCT_UC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_360", Value=2)]
      GCT_360 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_MI", Value=3)]
      GCT_MI = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_TENCENT", Value=4)]
      GCT_TENCENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GCT_MAX", Value=100)]
      GCT_MAX = 100
    }
  
}