//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Pay.proto
// Note: requires additional types generated from: ResultCode.proto
namespace SLMS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SynPayProductInfo")]
  public partial class SynPayProductInfo : global::ProtoBuf.IExtensible
  {
    public SynPayProductInfo() {}
    
    private string _productid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"productid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string productid
    {
      get { return _productid; }
      set { _productid = value; }
    }
    private int _buynum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buynum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buynum
    {
      get { return _buynum; }
      set { _buynum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csSynPayInfo")]
  public partial class csSynPayInfo : global::ProtoBuf.IExtensible
  {
    public csSynPayInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scSynPayInfo")]
  public partial class scSynPayInfo : global::ProtoBuf.IExtensible
  {
    public scSynPayInfo() {}
    
    private int? _monthcard_leftdays;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monthcard_leftdays", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monthcard_leftdays
    {
      get { return _monthcard_leftdays?? default(int); }
      set { _monthcard_leftdays = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool monthcard_leftdaysSpecified
    {
      get { return this._monthcard_leftdays != null; }
      set { if (value == (this._monthcard_leftdays== null)) this._monthcard_leftdays = value ? this.monthcard_leftdays : (int?)null; }
    }
    private bool ShouldSerializemonthcard_leftdays() { return monthcard_leftdaysSpecified; }
    private void Resetmonthcard_leftdays() { monthcard_leftdaysSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<SLMS.SynPayProductInfo> _productinfo = new global::System.Collections.Generic.List<SLMS.SynPayProductInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"productinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SLMS.SynPayProductInfo> productinfo
    {
      get { return _productinfo; }
    }
  
    private int? _permanent_card;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"permanent_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int permanent_card
    {
      get { return _permanent_card?? default(int); }
      set { _permanent_card = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool permanent_cardSpecified
    {
      get { return this._permanent_card != null; }
      set { if (value == (this._permanent_card== null)) this._permanent_card = value ? this.permanent_card : (int?)null; }
    }
    private bool ShouldSerializepermanent_card() { return permanent_cardSpecified; }
    private void Resetpermanent_card() { permanent_cardSpecified = false; }
    
    private uint? _next_monthcardaward_stamp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"next_monthcardaward_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_monthcardaward_stamp
    {
      get { return _next_monthcardaward_stamp?? default(uint); }
      set { _next_monthcardaward_stamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool next_monthcardaward_stampSpecified
    {
      get { return this._next_monthcardaward_stamp != null; }
      set { if (value == (this._next_monthcardaward_stamp== null)) this._next_monthcardaward_stamp = value ? this.next_monthcardaward_stamp : (uint?)null; }
    }
    private bool ShouldSerializenext_monthcardaward_stamp() { return next_monthcardaward_stampSpecified; }
    private void Resetnext_monthcardaward_stamp() { next_monthcardaward_stampSpecified = false; }
    
    private uint? _next_permanentcard_award_stamp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"next_permanentcard_award_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_permanentcard_award_stamp
    {
      get { return _next_permanentcard_award_stamp?? default(uint); }
      set { _next_permanentcard_award_stamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool next_permanentcard_award_stampSpecified
    {
      get { return this._next_permanentcard_award_stamp != null; }
      set { if (value == (this._next_permanentcard_award_stamp== null)) this._next_permanentcard_award_stamp = value ? this.next_permanentcard_award_stamp : (uint?)null; }
    }
    private bool ShouldSerializenext_permanentcard_award_stamp() { return next_permanentcard_award_stampSpecified; }
    private void Resetnext_permanentcard_award_stamp() { next_permanentcard_award_stampSpecified = false; }
    
    private uint? _next_doublecard_award_stamp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"next_doublecard_award_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_doublecard_award_stamp
    {
      get { return _next_doublecard_award_stamp?? default(uint); }
      set { _next_doublecard_award_stamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool next_doublecard_award_stampSpecified
    {
      get { return this._next_doublecard_award_stamp != null; }
      set { if (value == (this._next_doublecard_award_stamp== null)) this._next_doublecard_award_stamp = value ? this.next_doublecard_award_stamp : (uint?)null; }
    }
    private bool ShouldSerializenext_doublecard_award_stamp() { return next_doublecard_award_stampSpecified; }
    private void Resetnext_doublecard_award_stamp() { next_doublecard_award_stampSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"YYBParam")]
  public partial class YYBParam : global::ProtoBuf.IExtensible
  {
    public YYBParam() {}
    
    private string _openid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"openid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string openid
    {
      get { return _openid; }
      set { _openid = value; }
    }
    private string _openkey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"openkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string openkey
    {
      get { return _openkey; }
      set { _openkey = value; }
    }
    private string _pf;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pf
    {
      get { return _pf; }
      set { _pf = value; }
    }
    private string _pfkey;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pfkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pfkey
    {
      get { return _pfkey; }
      set { _pfkey = value; }
    }
    private int _session_type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"session_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int session_type
    {
      get { return _session_type; }
      set { _session_type = value; }
    }
    private string _item;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string item
    {
      get { return _item; }
      set { _item = value; }
    }
    private int? _amt;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"amt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int amt
    {
      get { return _amt?? default(int); }
      set { _amt = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool amtSpecified
    {
      get { return this._amt != null; }
      set { if (value == (this._amt== null)) this._amt = value ? this.amt : (int?)null; }
    }
    private bool ShouldSerializeamt() { return amtSpecified; }
    private void Resetamt() { amtSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csPaySeccess")]
  public partial class csPaySeccess : global::ProtoBuf.IExtensible
  {
    public csPaySeccess() {}
    
    private string _tradeno;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tradeno", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tradeno
    {
      get { return _tradeno; }
      set { _tradeno = value; }
    }
    private SLMS.YYBParam _yyb_param = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"yyb_param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SLMS.YYBParam yyb_param
    {
      get { return _yyb_param; }
      set { _yyb_param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scPaySeccess")]
  public partial class scPaySeccess : global::ProtoBuf.IExtensible
  {
    public scPaySeccess() {}
    
    private SLMS.ResultCode _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SLMS.ResultCode result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _productid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"productid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string productid
    {
      get { return _productid?? ""; }
      set { _productid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool productidSpecified
    {
      get { return this._productid != null; }
      set { if (value == (this._productid== null)) this._productid = value ? this.productid : (string)null; }
    }
    private bool ShouldSerializeproductid() { return productidSpecified; }
    private void Resetproductid() { productidSpecified = false; }
    
    private int? _buynum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buynum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int buynum
    {
      get { return _buynum?? default(int); }
      set { _buynum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buynumSpecified
    {
      get { return this._buynum != null; }
      set { if (value == (this._buynum== null)) this._buynum = value ? this.buynum : (int?)null; }
    }
    private bool ShouldSerializebuynum() { return buynumSpecified; }
    private void Resetbuynum() { buynumSpecified = false; }
    
    private int? _remain_currency;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"remain_currency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int remain_currency
    {
      get { return _remain_currency?? default(int); }
      set { _remain_currency = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool remain_currencySpecified
    {
      get { return this._remain_currency != null; }
      set { if (value == (this._remain_currency== null)) this._remain_currency = value ? this.remain_currency : (int?)null; }
    }
    private bool ShouldSerializeremain_currency() { return remain_currencySpecified; }
    private void Resetremain_currency() { remain_currencySpecified = false; }
    
    private int? _platform_errcode;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"platform_errcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int platform_errcode
    {
      get { return _platform_errcode?? default(int); }
      set { _platform_errcode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool platform_errcodeSpecified
    {
      get { return this._platform_errcode != null; }
      set { if (value == (this._platform_errcode== null)) this._platform_errcode = value ? this.platform_errcode : (int?)null; }
    }
    private bool ShouldSerializeplatform_errcode() { return platform_errcodeSpecified; }
    private void Resetplatform_errcode() { platform_errcodeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csGetCardAward")]
  public partial class csGetCardAward : global::ProtoBuf.IExtensible
  {
    public csGetCardAward() {}
    
    private uint _tp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tp
    {
      get { return _tp; }
      set { _tp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scGetCardAward")]
  public partial class scGetCardAward : global::ProtoBuf.IExtensible
  {
    public scGetCardAward() {}
    
    private SLMS.ResultCode _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SLMS.ResultCode result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}