//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ResultCode.proto
namespace SLMS
{
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Success", Value=0)]
      Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SystemErr", Value=1)]
      ERR_SystemErr = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_Unknown", Value=2)]
      ERR_Unknown = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PlayerNotExist", Value=3)]
      ERR_PlayerNotExist = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QueryNoData", Value=4)]
      ERR_QueryNoData = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QueryFail", Value=5)]
      ERR_QueryFail = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CommitFail", Value=6)]
      ERR_CommitFail = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DeleteFail", Value=7)]
      ERR_DeleteFail = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_AccountErr", Value=8)]
      ERR_AccountErr = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_TestVersion", Value=9)]
      ERR_TestVersion = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAX_ACCOUNT_ROLE_NUM", Value=20)]
      ERR_MAX_ACCOUNT_ROLE_NUM = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAX_PART_ROLE_NUM", Value=21)]
      ERR_MAX_PART_ROLE_NUM = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_OPT_FREQUENCY", Value=22)]
      ERR_OPT_FREQUENCY = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_BAD_NETWORK_CONDITION", Value=23)]
      ERR_BAD_NETWORK_CONDITION = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SESSION_ERROR", Value=24)]
      ERR_SESSION_ERROR = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CLIENT_VERSION", Value=25)]
      ERR_CLIENT_VERSION = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_INVALID_SERVER_STATUS", Value=26)]
      ERR_INVALID_SERVER_STATUS = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CONFIG_VERSION", Value=27)]
      ERR_CONFIG_VERSION = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_RoleNameExist", Value=1701)]
      ERR_RoleNameExist = 1701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_RoleNameNotLegal", Value=1702)]
      ERR_RoleNameNotLegal = 1702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_RoleNameEmpty", Value=1703)]
      ERR_RoleNameEmpty = 1703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_RoleNameNotChanged", Value=1704)]
      ERR_RoleNameNotChanged = 1704
    }
  
}