//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: SynTimer.proto
namespace SLMS
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimerInfo")]
  public partial class TimerInfo : global::ProtoBuf.IExtensible
  {
    public TimerInfo() {}
    
    private SLMS.TimerType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SLMS.TimerType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"csSynTimer")]
  public partial class csSynTimer : global::ProtoBuf.IExtensible
  {
    public csSynTimer() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"scSynTimer")]
  public partial class scSynTimer : global::ProtoBuf.IExtensible
  {
    public scSynTimer() {}
    
    private readonly global::System.Collections.Generic.List<SLMS.TimerInfo> _info = new global::System.Collections.Generic.List<SLMS.TimerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SLMS.TimerInfo> info
    {
      get { return _info; }
    }
  
    private int? _energy_point;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"energy_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int energy_point
    {
      get { return _energy_point?? default(int); }
      set { _energy_point = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool energy_pointSpecified
    {
      get { return this._energy_point != null; }
      set { if (value == (this._energy_point== null)) this._energy_point = value ? this.energy_point : (int?)null; }
    }
    private bool ShouldSerializeenergy_point() { return energy_pointSpecified; }
    private void Resetenergy_point() { energy_pointSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TimerType")]
    public enum TimerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_EMERGY", Value=0)]
      TT_EMERGY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TT_MAX_TIMER", Value=32)]
      TT_MAX_TIMER = 32
    }
  
}